version: '3'

services:
  app:
    build: ./
    container_name: 'webstore-java'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/webstore
      SPRING_DATASOURCE_USERNAME: webstore
      SPRING_DATASOURCE_PASSWORD: webstore
    ports:
      - '8080:8080'